###

GET http://localhost:3000/api/country/ma/guelmim-oued-noun


###
GET  http://localhost:3000/api/country/

###
POST http://localhost:3000/api/country/
[
   {
        "name": "morocco",
        "code" : "ma",
        "dialcode" : "+212",
        "curency" : "mad"   
     },
     {
        "name": "algerie",
        "code" : "dz",
        "dialcode" : "+213",
        "curency" : "dinar"
     }
     ]